language: node_js

node_js:
  - '10.0'

before_script:
  - npm install -g firebase-tools

script:
  - 

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master
