language: node_js

node_js:
  - '8.1'

sudo: required

cache:
  directories:
  - node_modules

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - npm test
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  on:
    branch: master
